const express = require("express");
const authRoutes = require("./authRoutes");
const doctorRoutes = require("./doctorRoutes");
const appointmentRoutes = require("./appointmentRoutes");
const slotRoutes = require("./slotRoutes");
const labRoutes = require("./labRoutes");
const pharmacyRoutes = require("./pharmacyRoutes");
const commerceRoutes = require("./commerceRoutes");
const paymentRoutes = require("./paymentRoutes");
const adminRoutes = require("./adminRoutes");
const subscriptionRoutes = require("./subscriptionRoutes");
const miscRoutes = require("./miscRoutes");
const planRoutes = require("./planRoutes");
const businessRoutes = require("./businessRoutes");
const partnerRoutes = require("./partnerRoutes");
const articleRoutes = require("../modules/articles/article.routes");
const chatRoutes = require("../modules/chat/chat.routes");
const labBookingRoutes = require("./labBookingRoutes");
const orderManagementRoutes = require("./orderManagementRoutes");
const packageRoutes = require("./packageRoutes");
const aiRoutes = require("../modules/ai/ai.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/doctors", doctorRoutes);
router.use("/appointments", appointmentRoutes);
router.use("/slots", slotRoutes);
router.use("/labs", labRoutes);
router.use("/pharmacy", pharmacyRoutes);
router.use("/", commerceRoutes);
router.use("/payments", paymentRoutes);
router.use("/admin", adminRoutes);
router.use("/", businessRoutes);
router.use("/", partnerRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/plans", planRoutes);
router.use("/", miscRoutes);
router.use("/v1/articles", articleRoutes);
router.use("/chat", chatRoutes);
router.use("/ai", aiRoutes);
router.use("/v1/lab-bookings", labBookingRoutes);
router.use("/v1/orders", orderManagementRoutes);
router.use("/", packageRoutes);

module.exports = router;
